version: '3'
services:
  postgres-olap:
    image: postgres:16
    environment:
      POSTGRES_USER: olap
      POSTGRES_PASSWORD: olap
      POSTGRES_DB: olap_db
    ports:
      - "5433:5432"
    volumes:
      # Volume anÃ´nimo para resetar dados a cada 'docker-compose down'
      # - postgres-olap-test-volume:/var/lib/postgresql/data
      - ../data_files:/data_files
      - ../scripts/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "olap", "-d", "olap_db"]
      interval: 10s
      retries: 5
      start_period: 5s

  spark-job:
    build:
      context: ..
      dockerfile: Dockerfile.spark
    volumes:
      - ./dags:/opt/spark/jobs
      - ./tests/data:/opt/spark/data
    environment:
      - SPARK_MODE=client
    command: >
      /opt/bitnami/spark/bin/spark-submit 
      --master local[2]
      --driver-memory 3g
      --executor-memory 3g
      --conf spark.driver.maxResultSize=1g
      --conf spark.sql.shuffle.partitions=50
      --conf spark.default.parallelism=4
      --conf spark.sql.adaptive.enabled=true
      --conf spark.sql.adaptive.coalescePartitions.enabled=true
      --conf spark.memory.fraction=0.6
      --conf spark.memory.storageFraction=0.2
      --conf spark.sql.autoBroadcastJoinThreshold=10485760
      --conf spark.sql.broadcastTimeout=600
      --conf spark.network.timeout=600s
      --conf spark.executor.heartbeatInterval=60s
      --jars /opt/bitnami/spark/jars/postgresql-42.7.3.jar 
      /opt/spark/jobs/spark_script.py 
      --dataset sih 
      --date 2023-01-01 
      --bucket local 
      --prefix /opt/spark/data 
      --pg-url jdbc:postgresql://postgres-olap:5432/olap_db
    depends_on:
      postgres-olap:
        condition: service_healthy

volumes:
  postgres-olap-test-volume:
